# Generated by Django 5.2.12 on 2026-05-25 20:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("region_name", models.CharField(max_length=100)),
                ("latitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=7, max_digits=10)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "LOW"),
                            ("MEDIUM", "MEDIUM"),
                            ("HIGH", "HIGH"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "db_table": "REGION",
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("original_file_name", models.CharField(max_length=255)),
                ("stored_file_name", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                ("thumbnail_path", models.CharField(blank=True, max_length=500)),
                (
                    "file_size",
                    models.BigIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "weather",
                    models.CharField(
                        choices=[
                            ("CLEAR", "CLEAR"),
                            ("CLOUDY", "CLOUDY"),
                            ("RAIN", "RAIN"),
                            ("FOG", "FOG"),
                            ("SNOW", "SNOW"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("date", models.DateTimeField()),
                ("fish_count", models.BigIntegerField(default=0)),
                ("skygazer_count", models.BigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROCESSING", "PROCESSING"),
                            ("COMPLETED", "COMPLETED"),
                            ("FAILED", "FAILED"),
                        ],
                        default="PROCESSING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "region",
                    models.ForeignKey(
                        db_column="region_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="videos",
                        to="videos.region",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "VIDEO",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DetectedTime",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("fish_type", models.CharField(max_length=50)),
                (
                    "start_time",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "end_time",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        db_column="video_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detected_times",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "db_table": "DETECTED_TIME",
            },
        ),
    ]
