# Generated by Django 5.2.12 on 2026-05-30 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("detail", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("UPLOAD", "업로드"),
                            ("DOWNLOAD", "다운로드"),
                            ("LOGIN", "로그인"),
                            ("LOGOUT", "로그아웃"),
                            ("ANALYSIS", "분석"),
                            ("DELETE", "삭제"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
