# Generated by Django 5.2.12 on 2026-05-28 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_basin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basin',
            old_name='region',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='basin',
            old_name='severity',
            new_name='risk_level',
        ),
    ]
